#2021-6-28

name: Build zerotier-moon docker Image 

on:
  push:
    paths:
    - '.github/workflows/zerotier-moon-buildx.yml'
  workflow_dispatch:

env:
  zerotier-moon_VER: 1.6.5

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./zerotier-moon
          file: ./zerotier-moon/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            hushunxu/zerotier-moon:latest
            hushunxu/zerotier-moon:${{ env.zerotier-moon_VER }}

#https://github.com/marketplace/actions/docker-hub-description Docker Hub Personal Access Tokens cannot be used as they are not supported by the API
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
         DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         DOCKERHUB_REPOSITORY: hushunxu/zerotier-moon
         README_FILEPATH: ./zerotier-moon/README.md
